const ProjectsCon = [
  {
    id: 10,
    projectNumber: 10,
    projectName: 'Meme Generator',
    image: 'https://res.cloudinary.com/wimvb/image/upload/v1610890542/scrimba-meme-generator_h3spjh.jpg',
    hrefLink: 'https://boneswvb.github.io/deployed-scrimba-meme-generator/',
    alt: 'Photo of Meme Generator for Wim von Benecke',
    target: 'blank',
    comment: 'React project using API',
  },
  {
    id: 9,
    projectNumber: 9,
    projectName: 'Name Cards',
    image: 'https://res.cloudinary.com/wimvb/image/upload/v1610890791/scrimbaNameCard_xbya8c.jpg',
    hrefLink: 'https://boneswvb.github.io/deployed-scrimba-name-card/',
    alt: 'Photo of Name List for Wim von Benecke',
    target: 'blank',
    comment: 'React Project - no CSS',
  },
  {
    id: 7,
    projectNumber: 7,
    projectName: 'Math Quize',
    image: 'https://res.cloudinary.com/wimvb/image/upload/v1610890868/mathTesterApr19_psph7a.jpg',
    hrefLink: 'https://boneswvb.github.io/mathQuize/',
    alt: 'Photo of Math Quize program',
    target: 'blank',
    comment: 'JavaScript exercise',
  },
  {
    id: 6,
    projectNumber: 6,
    projectName: 'Robo-Friends',
    image: 'https://res.cloudinary.com/wimvb/image/upload/v1610890938/roboFriendsApr19_byyb6m.jpg',
    hrefLink: 'https://boneswvb.github.io/robo-friends-two/',
    alt: 'Photo of Robot contact details',
    target: 'blank',
    comment: 'React Project',
  },
  {
    id: 4,
    projectNumber: 4,
    projectName: 'To Do List',
    image: 'https://res.cloudinary.com/wimvb/image/upload/v1610891022/toDoListApr19_w9r0yf.jpg',
    hrefLink: 'https://boneswvb.github.io/to-do-list/',
    alt: 'Photo of To Do List',
    target: 'blank',
    comment: 'JavaScript exercise - Minimal HTML and CSS',
  },

  {
    id: 3,
    projectNumber: 3,
    projectName: 'Quote Generator',
    image: 'https://res.cloudinary.com/wimvb/image/upload/v1610891128/randomQuoteGeneratorJan19_z2ff3v.jpg',
    hrefLink: 'https://codepen.io/Bones1/full/KymeoR',
    alt: 'Photo of quote generator',
    target: 'blank',
    comment: 'HTML, CSS, and JavaScript',
  },
  {
    id: 2,
    projectNumber: 2,
    projectName: 'Radio Vision 3.0.1',
    image: 'https://res.cloudinary.com/wimvb/image/upload/v1610891218/rediovisionWebOldJan19_tkmo2c.jpg',
    hrefLink: 'http://www.radiovision.co.za',
    alt: 'Photo of Radio Vision web site',
    target: 'blank',
    comment: 'HTML and CSS',
  },
  {
    id: 1,
    projectNumber: 1,
    projectName: 'Tribute to Gen. De La Rey',
    image: 'https://res.cloudinary.com/wimvb/image/upload/v1610891316/tributeJan19_ztekui.jpg',
    hrefLink: 'https://codepen.io/Bones1/full/OOXPBo',
    alt: 'Photo of Genral De Le Ray',
    target: 'blank',
    comment: 'HTML and CSS',
  },
];

export default ProjectsCon;
